### Start by loading in data

- UN text data
- GDP data
- climate associated words data

In [2]:
import os

"""
GETTING THE TEXT DATA FROM FOLDER DATA/TXT
"""



def get_text_data(output=False, N=False):
    """
    gets all the text data from the subfolders, can print it and you can limit the number of prints
    returns a dictionary with key the title of the file and value the text of the file
    """
    subfolders = []
    for folder in os.listdir('data/TXT'):
        if os.path.isdir(os.path.join('data/TXT', folder)):
            subfolders.append(folder)

    text_data = {}
    for folder in subfolders:
        for file in os.listdir(os.path.join('data/TXT', folder)):
            if file.endswith('.txt'):
                with open(os.path.join('data/TXT', folder, file), 'r') as f:
                    text_data[file] = f.read()
                    if output:
                        print(f"Title: {file}")
                        print(f"Text: {text_data[file]}")
                        print("\n")
                    if N and len(text_data) >= N:
                        return text_data
    return text_data

#test with first file
text_data = get_text_data()
print(text_data["ARG_01_1946.txt"])

At the resumption of the first session of the General Assembly, the Argentine delegation wishes to state its views on a number of questions.
Politics are determined by circumstances. Accordingly, in making these remarks, we do not renounce the right to take decisions in the light of events; but we nevertheless think it desirable to state here certain useful principles to serve as a guide for our actions. We hope that these remarks will be interpreted at their true value. We are not sceptics, but our relative optimism would be strengthened if we found that a spirit of conciliation were gaining ground. Otherwise, we should be obliged to resume complete freedom of action, and proceed in accordance with the circumstances and the interests of the country which we represent.
We are no friends of unanimity, which is wont to disguise undesirable, if not improper pressure. Even the hottest debates in the defence of conflicting points of view are not incompatible with the desire to reach a solution. We are met here to ensure and maintain international peace and security, and not to lay the foundations of another conflict. The purpose of our deliberations is to reach positive decisions as equitable as our respective interests permit, and not to separate after heated controversies without having done anything useful.
Hence, we realize that it is necessary to compromise. Nations, like individuals, when they meet to debate and solve problems which concern them equally, must not believe themselves to be in possession of the only real truth. Each of them may, and perhaps should, believe, that its own particular conception of the truth is the best; but when the respective truths differ, insistence is out of place. The world, or if you prefer it, the man in the street, may regard such insistence as deliberate and as being maintained with the sole object of preventing a solution being reached.
Between perfect accuracy and complete error there are many degrees which are acceptable in proportion to their closeness to the particular conception of truth that each of us personally upholds. A decision must be taken in favour of one of them, and clearly that must be the one which reconciles the greatest possible number of opinions.
In making this assertion, it is not my intention to defend solutions adopted against the wish of substantial minorities, as is done to solve internal problems in countries governed by representative assemblies. I think it would be very difficult to make people submit to the decisions of a universal parliament, primarily because such a parliament would be very difficult to organize. But when an international assembly obtains a majority of sixty-five per cent, seventy per cent or seventy-five per cent of the countries represented, the minority must recognize that this exceptional majority has at least as good intentions as those by which it is itself animated.
Otherwise we should have to recognize that we have come here not to hold discussions, exchange impressions and, if necessary, accept suggestions, but to impose our truth which in such circumstances would be identical with our will, not to say our whim. If that were so, it would be better to stay at home and await events.
But the fact is that the last war was fought against such a system, and we, even though we did not take part in it, knew that it was fought with real justification. Even if we admit that every people is governed in the manner best suited to it within its own frontiers, it is not possible to live with peoples who claim to impose their particular truths or, if you like, their ideology on others. Is it not on that account that the regimes of Hitler and Mussolini met their downfall? Has the San Francisco Charter been signed in order to choose a new overlord, and are we meeting here for that purpose?
When faced with international problems which appeared to be insoluble, Argentina has always had recourse to arbitration. In the political field this Assembly must be the arbitrator; in the legal field, the International Court of Justice. If that procedure is followed in the future, when a nation believes it has lost its case either here or at The Hague, it can nevertheless feel satisfied, because the worst of verdicts will always be more favourable to it than the best of wars, if wars can be anything but bad. A good example, moreover, will always have a good influence and that nation will have contributed toward maintaining international peace and security.
Is it not on the basis that Roosevelt and Churchill signed the Atlantic Charter? Is it not with that purpose that we signed the San Francisco Charter? Is it not a fact that the great Powers have promised the world to act in good faith? It is precisely their economic and military power which places upon them the obligation to fulfill that promise.
I referred just now to arbitration in regard to my own country; permit me to dwell further on that matter.
We have solved our frontier differences with Chile, Paraguay and Brazil by means of arbitration. In the first case, His Britannic Majesty’s Government was the arbitrator. A decision was reached, and the boundaries were fixed in accordance therewith. We now maintain the most cordial relations with Chile.
Need I recall that, at the end of the last century, we were on the brink of war? Need I recall that the embrace of Presidents Roca and Errazurriz at the Straits of Magellan and the signing of the May pacts which followed, consolidated our friendship with our sister Republic?
The Treaty of Alliance signed in 1865 with Brazil and Uruguay, before the war against Marshal Lopez was started, entitled us to incorporate in our territory the whole of the Chaco as far as Bahia Negra. When peace was signed, we did not make use of the rights we had earned by our victory; we ceded the territories to the north of the Verde River and in face of the Paraguayan Government’s opposition in regard to the rest, we submitted to arbitration, by the President of the United States of America, our rights to the lands between the said river and Pilcomayo. President Hayes decided in favour of Paraguay, and since then we have cultivated relations of brotherly friendship with the Paraguayan people.
Mariano Varela, Sarmiento’s Minister for Foreign Affairs, expressed the point of view of the Argentine Foreign Office in a saying which some have called ingenuous, but which I regard as magnificent: “Victory does not entitle the victors to fix at their discretion their territorial boundaries with the vanquished.”
In 1889 we had drafted a frontier agreement with the Brazilian Empire: we were discussing the ownership of an area of twenty-five thousand square leagues in Misiones. When the Republic was proclaimed in November of that year the Brazilian Congress refused to approve the agreement. We then submitted the dispute for arbitration, again to the President of the United States of America. Mr. Cleveland decided in favour of Brazil, and to this day we are maintaining the closest relations with our neighbour in the north, whose territory is three times larger than that of Argentina.
After a century of direct negotiations during which incidents occurred that in other countries might have led to war, we fixed our frontier with Bolivia.
We maintain that arbitration is a juridical procedure which must be incorporated in public international law with universal application if we wish to avoid war. We have signed treaties of this kind, which are in force at present, with Uruguay, Paraguay, Bolivia, Chile, Brazil, Italy, Ecuador, Venezuela, Colombia, France and Spain.
Were the Argentinian people in agreement with these decisions which deprived us of extensive territories in the Chaco and Misiones? They certainly were not, for our rights in both cases appeared to be indisputable. But the members of the Government and the press reminded them that “a verdict once given must be held as truth,” and the people returned to their work, that noble work which, in the material sense, enabled us, within a short time, to produce one hundred times the value of the territories lost, and in the moral sense gave the people the satisfaction of feeling that they were taking their place in the vanguard of universal civilization.
Personally, I think that those arbitration verdicts were just, because we believe in the justice of arbitration even when the verdict is against us.
Such antecedents prove that we are a peace- loving people, respecting, as much as any, the rights of other nations; we cannot accept without protest any attempt to represent us in a different light. The facts contained in the record of history establish beyond doubt who is speaking the truth.
Do we hope to grow, to increase our population, to create wealth and distribute it, so that none of our people may lack the means necessary to provide them with shelter, clothing, footwear, food, education; in short, with at least the minimum of dignity which the human personality requires? We do, indeed: but that aspiration, whilst representing an unquestionable right, is also a duly in which we must not fail. Our country can support a hundred million inhabitants and we are ready to work to that end, so that the prophesy of Sarmiento, our great visionary, may be fulfilled. In acting thus we in no way desire to encroach upon the interests, or wound the susceptibilities, of any other nation. On the contrary, we shall help towards the solution of the acute social and economic problems caused by the. war, which might lead to the downfall of present-day civilization.
Have not we, the united Provinces of the south, before our eyes the great example of the United States of the north, this mighty country which is our host? We desire to follow that example. When all the nations of the earth have reached a similar stage of development, the two thousand million human brings dial inhabit it will be much happier. It is towards that goal that civilization must aspire.
But to return to the question of arbitration and our international tradition.
Once when the composer Verdi was invited to attend the rehearsal of an unpublished musical score, he sat down in an armchair with his hat on. Someone noticed that from time to time during the performance the composer doffed his hat. When it was over, they asked him why he had done this and Verdi replied “I was greeting old friends." He was referring to certain musical motifs in the work he had just heard which he had written himself.
We Argentines, on reading the Atlantic Charter and some of the provisions of the San Francisco Charter, doff our hats respectfully, greeting principles which are now embodied in public international law and with which we had long been familiar.
But our attitude is not based on pretentious claims. We do not claim to be, the authors of these formulae; we simply rejoice that some noble juridical principles, which our country has defended, have been accepted by the great Powers of the earth.
If the policy of neutrality maintained by our Government throughout both world wars led us along the wrong road, we have always retraced our steps, and that must suffice.
Some neutral countries, very honourable ones moreover, abandoned their isolation through force of circumstances. Others maintained their attitude in the face of every difficulty. Allow me to say in passing, and it should be fully recognized, that the Argentine people have always been opposed to aggressors. We have never started a war. On the two occasions when we were obliged to resort to arms, we had been provoked; in both cases we won and our victory was also a victory for freedom and justice.
Out of the first war, a new nation, today a most progressive one, came into existence; after the second, not only did we refrain from annexing the territories we had been promised, but, as I have already said, we lost many thousands of square kilometres of land. All this happened in the course of a short and somewhat turbulent existence.
After the wars of independence, we fell first into anarchy and then into a dictatorship. It was only in 1853 that we provided ourselves with a Constitution, and it was not until 1862 that the country was finally organized. Nevertheless, as early as 1813, the Assembly of the united Provinces of the south had abolished slavery and during the period of tyranny we practised arbitration and withstood foreign interference.
Between then and 1880, the year in which the organization of the country was completed by the federalization of the city of Buenos Aires, there were three presidencies, historic in the greatness and in the qualities of the men who held that office. Barely seventy years have passed since then. In 1912, we achieved electoral freedom, but the freely elected governments did not succeed in interpreting the aspirations of a great part of the people who had put them in office.
A social revolution which was started by a de facto government in 1943 is now being completed by the constitutional government elected in February of this year; this was necessary before any improvement in the balance of economic factors could take place.
This shows that the Argentine people have always succeeded in asserting themselves at every stage of their history between 1862 and the present time. It also shows that, although they sometimes made mistakes, they rectified them in the end. But all this is exclusively our own history, and although we certainly cannot deny anyone the right to pass judgment upon us, to applaud our wise actions and blame our mistakes, we do not and never shall allow foreign interference in any matter concerning the right of our people to decide their own destiny inside the boundaries of the territory which fate has given us.
From the time they achieve their independence, nations are sovereign States, equal before the law and not subject to any interference from outside unless it be with their own free consent.
In speaking on this subject before this Assembly, and in recalling this principle, which is a part of our international political tradition, it would be unjust not to refer to Louis Maria Drago. As long ago as December 1902, this Argentine Prime Minister, by denying the great European Powers the right to obtain, by the presence of their fleets in the waters of the debtor nation, the repayment of loans made by certain of their nationals, upheld the right of men and nations to live at peace, free from fear.
The United Nations Charter recognizes all these noble principles to which I have referred; that is why we signed it and we are naturally determined to support it.
Passing to another subject, I wish to affirm our solidarity, first and foremost, with all the nations of America from Cape Horn to Hudson Bay, and to state that we support the purposes and principles set forth in the San Francisco Charter for the establishment and the maintenance of international peace and security and that we have co-operated, and shall continue to co-operate, in the material rehabilitation of the world. That is why we are here.
I have just referred to the San Francisco Charter, the multilateral international treaty that binds us together. No one can pretend that it cannot be improved. For our own part, we maintain that it must be improved. Experience has shown that the privilege granted to five Powers to invalidate even those resolutions which have been unanimously adopted, has not yielded the results which was expected of it when it was established. It should not therefore be retained, especially as it openly contradicts the very provisions of the Preamble and the purposes and principles upon which the Charter is based. The Argentine delegation has already said that at San Francisco; the only reason why it did not object to the original text, as approved, was because it acknowledged that in certain given circumstances, what is legally just and desirable may not be politically possible. But it added that experience would show whether a reform was appropriate or necessary.
Experience has eloquently proved that, so far, this privilege has not operated in defence of the basic principles underlying the United Nations Charter.
This is not the time to attempt a demonstration of this point. As, however, I know something of the motives which led to the approval of the clause which I am criticizing I shall restrict myself to saying that the privilege referred to is not conducive to reasoned discussion such as will lead to compromises and agreements; on the contrary, it invites obstinate defence of one-sided points of view and therefore leads to differences and to the abandonment of any constructive action.
This privilege should be suppressed and replaced by the system of a two-thirds or three-quarters majority vote by the body concerned.
This system should operate for the executive organ, namely, the Security Council. The privilege has, however, been extended to the question of the reform of the Charter, which cannot be effected without the unanimous approval of the same five Powers. I maintain that in this case it becomes not a privilege but an absurdity. The first time an attempt is made to exercise such an unjustified right, there will be no other practical solution but to dissolve the Organization and set it up again immediately on a non-privilege basis: that alone demonstrates the absurdity of the situation.
However, pending the solution of this difficulty, we must not remain idle. We are confronted by serious problems; reconstruction of the devastated areas; codification of international law, so that the principles of freedom and justice, for which the second world war was fought, shall be universally established; and, above all, the establishment of social security, so that by one means or another and in proportion to the economic resources of each country, free men throughout the world may know that they are indeed equal and may exercise the right to live, while enjoying the essential minimum standard of decency compatible with human dignity.
I do not wish to conclude this address without making an appeal to the highest sentiments of my colleagues here. After the first world war, the Allied and Associated Powers laid the foundations of the League of Nations. For reasons which it is not fitting to dwell upon here, the League failed; but not to the extent of preventing statesmen from returning to the idea after the second world war.
Most of the free nations of the world are represented here. The United States of America, which at that time preferred to remain aloof, is now taking a leading part and working with the greatest enthusiasm. The material assets of the former League have been transferred to us; and dominating the whole scene is the spirit of that great visionary of peace and enlightened democrat, Woodrow Wilson, whose life unfortunately came to an end in the midst of the onerous task which he had undertaken. We are in the country of his birth. Let us raise our thoughts towards him and place this Assembly under his auspices. Let us pledge ourselves to work with enthusiasm, but also with the tolerance needed to co-ordinate the tasks entrusted to us.
This continent of America, whose welfare we all have at heart, should not be the permanent home of a civilization which has fled from a shaken and devastated Europe, but merely the temporary refuge in which people from the old world, who have come here to face the task of preserving and developing its civilization, may find peace of mind. We can and must show the peoples of the world, who are now at peace and are striving for welfare and progress, that in planning the future happiness of the young nations — our own happiness — we do not contemplate the downfall of the old-established human civilizations, which preceded us in history and to which we owe a large part of what we have and what we are.

In [17]:
import keyword
import regex as re

climate_words_dict = {"greenhouse_gases_and_emissions": [
        "carbon dioxide", "co2", "methane", "ch4", "nitrous oxide", "n2o",
        "fluorinated gases", "greenhouse effect", "carbon emissions",
        "scope 1 emissions", "scope 2 emissions", "scope 3 emissions",
        "carbon footprint", "carbon budget", "emission intensity", "flaring"
    ],
    "climate_science_and_phenomena": [
        "global warming", "surface temperature", "temperature anomaly",
        "radiative forcing", "albedo effect", "feedback loop", "tipping point",
        "keeling curve", "ocean acidification", "paleoclimatology", "antarctic ice sheet",
        "arctic sea ice", "permafrost thawing", "glacier retreat", "thermohaline circulation",
        "el nino", "la nina", "enso", "polar vortex"
    ],
    "extreme_weather_and_impacts": [
        "sea level rise", "storm surge", "coastal erosion", "flash drought",
        "megadrought", "heatwave", "heat dome", "wildfire", "forest fire",
        "tropical cyclone", "typhoon", "hurricane intensification",
        "biodiversity loss", "coral bleaching", "species extinction",
        "habitat fragmentation", "vector-borne disease", "water scarcity"
    ],
    "energy_and_technology": [
        "clean energy", "renewable energy", "solar photovoltaic", "wind turbine",
        "geothermal", "hydroelectric", "nuclear energy", "grid storage",
        "battery storage", "green hydrogen", "electrification", "heat pump",
        "electric vehicles", "ev adoption", "carbon capture and storage", "ccs",
        "direct air capture", "dac", "bioenergy"
    ],
    "policy_agreements_and_economics": [
        "ipcc", "cop28", "cop29", "cop30", "paris agreement", "unfccc",
        "nationally determined contributions", "ndc", "carbon pricing",
        "carbon tax", "cap and trade", "emissions trading system", "ets",
        "esg", "green finance", "loss and damage", "carbon border adjustment mechanism",
        "cbam", "net zero", "carbon neutrality", "climate justice"
    ],
    "adaptation_and_nature_solutions": [
        "climate adaptation", "climate resilience", "afforestation",
        "reforestation", "blue carbon", "mangrove restoration",
        "regenerative agriculture", "soil carbon sequestration",
        "rewilding", "sponge cities", "flood defense", "sea wall"
    ], 
    "school": [
        "school", "education", "curriculum", "teacher", "student",
        "classroom", "lesson", "learning", "teaching", "pedagogy", "university", "college", "schooling", "academic", "syllabus",
        "schooling", "academic", "syllabus", "instruction", "training",
        "schoolwork", "homework", "assignment", "exam", "test", "assessment", "grading", "evaluation", "classroom management",
        "school policy", "school"]
}

In [16]:
# load GDP.csv data 
import pandas as pd
gdp = pd.read_csv("data/GDP.csv")
gdp

# list_of_countries = gdp['Country'].unique().tolist()

,Country,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.727933e+09,2.791061e+09,2.963128e+09,2.983799e+09,3.092179e+09,3.276188e+09,3.395794e+09,2.610039e+09,3.126019e+09,NaN
1,Africa Eastern and Southern,AFE,2.112502e+10,2.161623e+10,2.350628e+10,2.804836e+10,2.592067e+10,2.947210e+10,3.201437e+10,3.326951e+10,...,9.859871e+11,1.006526e+12,9.273485e+11,8.851764e+11,1.021043e+12,1.007196e+12,1.000834e+12,9.275933e+11,1.081998e+12,1.169484e+12
2,Afghanistan,AFG,5.377778e+08,5.488889e+08,5.466667e+08,7.511112e+08,8.000000e+08,1.006667e+09,1.400000e+09,1.673333e+09,...,2.056449e+10,2.055058e+10,1.999814e+10,1.801955e+10,1.889635e+10,1.841886e+10,1.890450e+10,2.014345e+10,1.458314e+10,NaN
3,Africa Western and Central,AFW,1.044764e+10,1.117321e+10,1.199053e+10,1.272769e+10,1.389811e+10,1.492979e+10,1.591084e+10,1.451058e+10,...,8.339481e+11,8.943225e+11,7.686447e+11,6.913634e+11,6.848988e+11,7.670257e+11,8.225384e+11,7.864600e+11,8.444597e+11,8.778633e+11
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.334016e+11,1.372444e+11,8.721930e+10,4.984049e+10,6.897277e+10,7.779294e+10,6.930911e+10,5.024137e+10,6.568544e+10,1.067136e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.735328e+09,7.074393e+09,6.295845e+09,6.682674e+09,7.180769e+09,7.878763e+09,7.899741e+09,7.717143e+09,9.412034e+09,9.429156e+09
262,"Yemen, Rep.",YEM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.041523e+10,4.322859e+10,4.244449e+10,3.131782e+10,2.684223e+10,2.160616e+10,NaN,NaN,NaN,NaN
263,South Africa,ZAF,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,1.421139e+10,1.582139e+10,...,4.008860e+11,3.811989e+11,3.467098e+11,3.235855e+11,3.814488e+11,4.041589e+11,3.885312e+11,3.376196e+11,4.190156e+11,4.058697e+11
264,Zambia,ZMB,7.130000e+08,6.962857e+08,6.931429e+08,7.187143e+08,8.394286e+08,1.082857e+09,1.264286e+09,1.368000e+09,...,2.803724e+10,2.714102e+10,2.125122e+10,2.095841e+10,2.587360e+10,2.631151e+10,2.330867e+10,1.811064e+10,2.214765e+10,2.978445e+10
265,Zimbabwe,ZWE,1.052990e+09,1.096647e+09,1.117602e+09,1.159512e+09,1.217138e+09,1.311436e+09,1.281750e+09,1.397002e+09,...,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,1.758489e+10,3.415607e+10,2.183223e+10,2.150970e+10,2.837124e+10,2.067806e+10

In [62]:
#load pisa scores
pisa_df = pd.read_csv("data/average-performance-of-15-year-old-students-by-subject.csv")
pisa_df["average"] = pisa_df[["Mathematics", "Reading", "Science"]].mean(axis=1)
pisa_df_country = pisa_df.groupby("Entity").sum()
# display(pisa_df[pisa_df["Entity"]=="United States"], pisa_df[pisa_df["Entity"]=="Albania"])

pisa_df_filtered = pisa_df.groupby("Entity").filter(lambda g: len(g) > 7)
pisa_df_per_country = pisa_df_filtered.groupby(["Entity", "Year"]).sum()
# pisa_df_per_country
pisa_df_per_country

                   Code  Mathematics    Science    Reading     average
Entity        Year
Australia     2000  AUS      0.00000    0.00000  528.27850  528.278500
              2003  AUS    524.26600    0.00000  525.42700  524.846500
              2006  AUS    519.90780  526.87960  512.89330  519.893567
              2009  AUS    514.34045  527.27050  514.90063  518.837193
              2012  AUS    504.15076  521.49475  511.80400  512.483170
...                 ...          ...        ...        ...         ...
United States 2009  USA    487.39650  502.00226  499.82680  496.408520
              2012  USA    481.36680  497.40982  497.58173  492.119450
              2015  USA    469.62848  496.24243  496.93510  487.602003
              2018  USA    478.24472  502.38004  505.35278  495.325847
              2022  USA    464.88803  499.41406  503.93756  489.413217

[264 rows x 5 columns]

## EDA
from the dataframe of PISA scores, we can for example take Albania and USA. Albania does not have a record for each 3 years

## clean the text data and first scan

### speech data
---
We will use nltk module "stopwords" to remove stop words from the text data. 
The analysis will mainly focus on finding certain words in the text. By removing stop words, we do not have to match those words against words we are looking for. This will speed up the analysis. 
Furthermore, when doing a broader sentiment analysis, stop words will not be usefull and only make the text less information dense.

After removing stop words, we will quicky count the number of words per speech per country. This gives an indication of how long the speeches are and if they differ in lenght. This information is not needed for the final analysis, but helps with understanding the data.

### PISA score data
---
there are 88 countries in the PISA score data. If we only look at countries with entries from 2003 to 2022, there are 31 remaining. It is not needed to drop those countries, since we will predict PISA based on speeches from that country the year before.

In [ ]:
import nltk
nltk.download('stopwords')

def speech_set(text_data):
    """
    replaces dict value with set instead of list
    """
    for key in text_data:
        text_data[key] = set(text_data[key].split())
    return text_data

def speech_set_no_stopwords(text_data):
    """
    removes stopwords (input should be set so call speech_set first)
    """
    stopwords = set(nltk.corpus.stopwords.words('english'))
    
    for key in text_data:
        text_data[key] = text_data[key] - stopwords
    return text_data



text = speech_set(text_data)
text = speech_set_no_stopwords(text)

[nltk_data] Downloading package stopwords to /Users/jacob/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [6]:
# each key starts with 3 letter code. 
# generate new dict with key as 3 letter code and as value the number of words that appear in text (keys can have same 3 letter as beginning, so add those to the total)
word_count = {}
for key in text:
    token = key[:3]
    if token not in word_count:
        word_count[token] = []
    word_count[token].append(len(text[key]))

for key in word_count:
    word_count[key] = sum(word_count[key])/len(word_count[key])

sorted_word_count = sorted(word_count.items(), key=lambda x:x[1], reverse=True)

### counting the number of mentions of climate associated words
Combining the data from the UN speeches and the climate associated words, we can count the number of mentions of climate associated words per speech per country per year. We will store it by country, topic and year.

In [18]:
from turtle import rt
import pandas as pd
import re

records = []

for country_speech_year, speech_tokens in text.items():

    if "DS_Store" in country_speech_year:
        continue  
    
    country = country_speech_year[:3]
    year = int(country_speech_year[-8:-4])
   
    speech_str = " ".join(speech_tokens)
    
    for topic, word_list in climate_words_dict.items():
        pattern = re.compile(r"\b(" + "|".join(re.escape(w) for w in word_list) + r")\b", re.IGNORECASE)
        matches = pattern.findall(speech_str)
        
        if matches:
            records.append({
                "country": country,
                "year": year,
                "topic": topic,
                "mention_count": len(matches),
                "matched_words": list(set(m.lower() for m in matches))
            })

df_climate = pd.DataFrame(records)

In [20]:
df_climate[df_climate["topic"]=="school"]

,country,year,topic,mention_count,matched_words
0,BEL,1950,school,1,[lesson]
1,FRA,1950,school,1,[test]
2,TUR,1950,school,2,[test]
3,BRA,1950,school,1,[education]
4,DOM,1950,school,2,[lesson]
...,...,...,...,...,...
7526,VEN,2014,school,1,[education]
7527,LIE,2014,school,1,[learning]
7528,AZE,2014,school,1,[education]
7530,ISL,2014,school,4,"[university, test, training, education]"
7531,HUN,2014,school,1,[learning]

In [8]:
# now we will count how often each country names other countries using country_list as check
records = []
for country_speech_year, speech_tokens in text.items():
    if "DS_Store" in country_speech_year:
        continue  
    
    country = country_speech_year[:3]
    year = int(country_speech_year[-8:-4])
    
    speech_str = " ".join(speech_tokens)
    
    for other_country in list_of_countries:
        if other_country.lower() in speech_str.lower():
            records.append({
                "country": country,
                "year": year,
                "mentioned_country": other_country
            })  

df_mentions = pd.DataFrame(records)

In [15]:
# rework the df such that it lists how often a country is mentioned by another one (instead of who's mentioning whom)
# df_mentions_count = df_mentions.groupby(['mentioned_country', 'country'])
df_mentions[df_mentions["year"]==2020]

      country  year mentioned_country
32992     ISL  2020           Belarus
32993     ISL  2020           Georgia
32994     ISL  2020           Iceland
32995     ISL  2020             Libya
32996     ISL  2020           Ukraine
...       ...   ...               ...
33916     AND  2020             World
33917     BHR  2020           Bahrain
33918     BHR  2020            Israel
33919     BHR  2020             Libya
33920     BHR  2020             World

[929 rows x 3 columns]

In [ ]:
from numpy import disp


df_climate_topic = df_climate.groupby(['country', 'topic']).sum('mention_count').drop(columns=['year'])

df_climate_total = df_climate.groupby(['country']).sum('mention_count').drop(columns=['year'])


df_pivot = df_climate_topic.pivot_table(
    index='country',
    columns='topic',
    values='mention_count',
    aggfunc='sum',
    fill_value=0
)
df_pivot

topic,adaptation_and_nature_solutions,energy_and_technology,extreme_weather_and_impacts,greenhouse_gases_and_emissions,policy_agreements_and_economics
country,,,,,
AFG,0,2,1,0,0
AGO,0,2,0,0,1
ALB,0,4,0,0,0
AND,0,2,0,0,2
ARE,0,0,0,0,2
...,...,...,...,...,...
YMD,0,1,0,0,0
YUG,0,0,0,2,0
ZAF,0,0,0,0,2
ZMB,0,2,0,0,3
ZWE,0,0,0,0,1

In [ ]:
display(df_climate_total, df_climate_topic, df_climate_total[df_climate_total['mention_count'] >= 10])

         mention_count
country
AFG                  3
AGO                  3
ALB                  4
AND                  4
ARE                  2
...                ...
YMD                  1
YUG                  2
ZAF                  2
ZMB                  5
ZWE                  1

[170 rows x 1 columns]

                                         mention_count
country topic
AFG     energy_and_technology                        2
        extreme_weather_and_impacts                  1
AGO     energy_and_technology                        2
        policy_agreements_and_economics              1
ALB     energy_and_technology                        4
...                                                ...
YUG     greenhouse_gases_and_emissions               2
ZAF     policy_agreements_and_economics              2
ZMB     energy_and_technology                        2
        policy_agreements_and_economics              3
ZWE     policy_agreements_and_economics              1

[320 rows x 1 columns]

         mention_count
country
BFA                 10
DMA                 12
FJI                 12
FSM                 26
ISL                 25
KEN                 13
KHM                 11
LCA                 10
MDG                 10
PLW                 11
PNG                 12
PRY                 23
SLB                 28
TUV                 14
UGA                 12
WSM                 10